database:
  host: "localhost" # 数据库地址
  port: 5432  # 数据库端口
  user: "blockim"  # 名称
  password: "blockim"  # 密码
  dbname: "blockim"  # 数据库
  mongoHost: "localhost" # Mongo地址
  mongoPort: 27017 # Mongo端口
  mongoUser: "mongo" # Mongo用户
  mongoPassword: "mongo" # Mongo密码
  mongoDBName: "mongo" # Mongo库名
app:
  name: "BlockIM"
  appHost: "localhost:8080"
  frontHost: "localhost:5137"
smtp:
  smtpHost: "smtp.your.com"
  smtpPort: 114514
  smtpUser: "your_email"
  smtpPassword: "your_pass"
